on:
  push:
    branches: [ main ]

jobs:
  hello_world_job_public:
    runs-on: ubuntu-latest
    name: test task public run

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Redoc and Speccy petstore.yml
        id: redoc_speccy_petstore
        uses: therealagentk/redoc-cli-speccy-action@1.3.0
        with:
          # redoc-args: 'bundle test/petstore.yml -o redoc-output-accountAPI.yaml'
          speccy-args: 'lint --skip openapi-tags-alphabetical accountAPI.yaml'

      - name: Check result
        run: |
          ls -al
          (test -f lint --skip openapi-tags-alphabetical swiss-ng-api.yaml) || (echo "Missing an output file from previous step." && exit 1)
      - name: Get the output time
        run: echo "The time was ${{ steps.redoc_speccy_petstore.outputs.time }}"
